name: build-test-deploy #descriptive title for your workflow
# Note: Jobs are independent so steps are scoped locally and need to be repeated for every job

# set the event trigger
on: push

# define the jobs that we want to occur within this workflow
jobs:

# Job 1: Build an app
  build:

  # define a runner for this job
    runs-on: ubuntu-latest # GitHub hosted runner

    # Define steps and specific actions we want to occur within job
    steps:
      - name: checkout repos
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build

  # Job 2: Test the app
  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repos
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm test

  # Job 3: Deploy app
  deploy:

    # Enforces that jobs run in a sequential order, where the current job is contingent on the success of another job
    needs: test

    # define permissions to determine what our workflow is allowed to do
    permissions:
      contents: write
      pages: write
      id-token: write # token grants our workflow the power to access and tweak various parts of our repo, which is why it needs write access

    # define our deployment environment 
    # pinpoint our environment as our deployment destination by passing 'name' of environment and 'url' of deployment to the environment
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }} #snag url from the final deployment step

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo (with authentication)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: configure github pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      - run: npm install
      - run: npm run build
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out'
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
